variables:
  Major: '0'
  Minor: '1'
  Patch: '$(rev:r)'

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:

#- task: UseDotNet@2
#  displayName: 'Use .NET Core sdk'
#  inputs:
#    packageType: sdk
#    version: 2.2.x
#    installationPath: $(Agent.ToolsDirectory)/dotnet

# See: http://loudandabrasive.com/effective-nuget-versioning-in-azure-devops
- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
- script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch

# You need to install this into your DevOps org
# https://marketplace.visualstudio.com/items?itemName=gittools.gitversion
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: CsvParser/CsvParser.csproj
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion


