variables:
  Major: '0'
  Minor: '1'
  Patch: '$(rev:r)'

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.2.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

# You need to install this into your DevOps org
# https://marketplace.visualstudio.com/items?itemName=gittools.gitversion
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: CsvParser/CsvParser.csproj
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion


