trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:

#- task: UseDotNet@2
#  displayName: 'Use .NET Core sdk'
#  inputs:
#    packageType: sdk
#    version: 2.2.x
#    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetCommand@2
  displayName: Install and run GitVersion
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion

- task: CmdLine@2
  displayName: Run GitVersion
  inputs:
    script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    versioningScheme: byBuildNumber
    arguments: -c Release

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    nobuild: true
    arguments: -c Release 

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    arguments: -c Release --no-build

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;-:$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
    feedPublish: 'wb-artifacts'
    arguments: -c Release --no-build

