trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'CsvParser/CsvParser.csproj'
    